-- Create the expenses table
create table public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null,
  price numeric not null,
  category text not null,
  payment_method text not null,
  description text
);

-- Enable Row Level Security (RLS)
alter table public.expenses enable row level security;

-- Create policy to allow anonymous access (for demo purposes - restricted in production)
-- In a real app, you'd use authenticated users
create policy "Allow generic access"
on public.expenses
for all
using (true)
with check (true);
