-- Create the expenses table with user association
create table public.expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null default auth.uid(),
  date date not null,
  price numeric not null,
  category text not null,
  payment_method text not null,
  description text
);

-- Enable Row Level Security (RLS)
alter table public.expenses enable row level security;

-- Create policy to allow users to see only their own data
create policy "Users can view their own expenses"
on public.expenses
for select
using (auth.uid() = user_id);

-- Create policy to allow users to insert their own data
create policy "Users can insert their own expenses"
on public.expenses
for insert
with check (auth.uid() = user_id);

-- Create policy to allow users to update their own data
create policy "Users can update their own expenses"
on public.expenses
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Create policy to allow users to delete their own data
create policy "Users can delete their own expenses"
on public.expenses
for delete
using (auth.uid() = user_id);
